version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "hello world"
      - run:
        name: npm install
        command: npm install
