version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "hello world"
      - run: npm install

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
